GET http://localhost:3120/users


###
GET http://localhost:3120/users/622f42d9d6ca5ccffe34d79a



###
POST http://localhost:3120/users
Content-Type: application/json

{
"name": "Daryll Grainger",
"contact": "0681323110",
"email": "Daryllgrainger28z@gmail.com",
"password": "bigpoes"
}

###

DELETE http://localhost:3120/users/622f3c208a31b138956bfa80

###

PATCH http://localhost:3120/users/622f4c33902d5af0b51f4a1b
Content-Type: application/json

{
    "contact": "1234567890"
}
