GET http://localhost:3130/users


###
GET http://localhost:3110/users/623068c956702b5679d1c595



###
POST http://localhost:3130/products
Content-Type: application/json

{
"name": "jack daniels",
"price": 2200,
"category": "Whi2skey",
"img": "https://charlero5i-duty-free.com/media/catalog/product/j/a/jameson-irish-whiskey-400_2.jpg"

}

####

POST http://localhost:3130/users/login
Content-Type: application/json

{
"name": "James",
"email": "james28@gmail.com",
"password": "james",
"contact": "0681323110"

}

###



###

GET http://localhost:3130/products/623d6da6354809eb1df39c74

###

PUT http://localhost:3110/users/62397aa0b50f1cb282574212
Content-Type: application/json

{
    "name": "Johnathan"
}
#####
//FOR THE REGISTERING
######

PATCH http://localhost:3110/users/login
Content-Type: application/json

{

"email": "AAAAAAAAAAB@gmail.com",

"password": "AAAAAAaB"
}




####


POST http://localhost:3130/users/login
Content-Type: application/json

{
    "email":"daryllgraifewqfewqefwefnger28@gmail.com",
    "password":"hellewfweqfohi"

}

####

POST http://localhost:3130/contact
Content-Type: application/json

{
    "firstName": "daryll",
    "lastName": "grainger",
    "email": "jsiahdjk@gmail.com",
    "message": "i miss you"

}


