GET http://localhost:3130/users


###
GET http://localhost:3110/users/623068c956702b5679d1c595



###
POST http://localhost:3130/products
Content-Type: application/json

{
"name": "Jameson",
"price": 200,
"categories": "Whiskey",
"img": "https://charleroi-duty-free.com/media/catalog/product/j/a/jameson-irish-whiskey-400_2.jpg"

}

####

POST http://localhost:3130/users/login
Content-Type: application/json

{
"name": "James",
"email": "james28@gmail.com",
"password": "james",
"contact": "0681323110"

}

###



###

DELETE http://localhost:3110/users/623068c956702b5679d1c595

###

PUT http://localhost:3110/users/62397aa0b50f1cb282574212
Content-Type: application/json

{
    "name": "Johnathan"
}
#####
//FOR THE REGISTERING
######

PATCH http://localhost:3110/users/login
Content-Type: application/json

{

"email": "AAAAAAAAAAB@gmail.com",

"password": "AAAAAAaB"
}




####


POST http://localhost:3130/users/login
Content-Type: application/json

{
    "email":"daryllgraifewqfewqefwefnger28@gmail.com",
    "password":"hellewfweqfohi"

}